# @format

# global hooks
# supported keys:
# before_setup: Array of commands before all files are processd
# after_setup: Array of commands after all files are processed
# after setup
hooks:
# Files as array
# supported keys:
#   dst: filename to be saved
#   before_setup: Array of commands to executed before setup
#   after_setup: array of commands after setup
#   force_override: should override existing file
files:
  vim:
    src: "~/.vimrc"
    dst: "vimrc"
    before_setup:
      - "curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    after_setup:
      - vim +"PlugInstall --sync" +qa

  nvim:
    src: "~/.config/nvim/init.vim"
    dst: nvim_init.vim
    before_setup:
      - "sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"

    after_setup:
      - nvim +"PlugInstall --sync" +qa
  zsh:
    src: "~/.zshrc"
    dst: "zshrc"
    before_setup:
      - "wget -O $HOME/antigen.zsh git.io/antigen"
  tmux:
    src: "~/.tmux.conf.local"
    dst: tmux.conf.local
    before_setup:
      - "git clone https://github.com/gpakosz/.tmux.git ~/.tmux"
      - "ln -s -f .tmux/.tmux.conf $HOME/.tmux.conf"

  vimrc.d:
    src: "~/.vimrc.d"
    dst: vimrc.d
